"""nullable false countries

Revision ID: 012f1e3e4e87
Revises: bd9fff6f9535
Create Date: 2026-09-05 18:04:31.860958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012f1e3e4e87'
down_revision: Union[str, Sequence[str], None] = 'bd9fff6f9535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_text_trgm'), table_name='document_chunks', postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.execute("UPDATE documents SET countries = '{}' WHERE countries IS NULL")

    op.alter_column('documents', 'countries',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=2)),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'countries',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=2)),
               nullable=True)
    op.create_index(op.f('ix_document_chunks_text_trgm'), 'document_chunks', ['text'], unique=False, postgresql_ops={'text': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
