"""fix postgres array

Revision ID: 10ce27eafa4e
Revises: b963e93d4cfd
Create Date: 2026-09-05 18:19:19.417607

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "10ce27eafa4e"
down_revision: str | Sequence[str] | None = "b963e93d4cfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
