"""fix syntax

Revision ID: 28810b81378d
Revises: a4b10404324d
Create Date: 2026-09-08 00:14:38.739564

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '28810b81378d'
down_revision: str | Sequence[str] | None = 'a4b10404324d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
