"""add embedding model

Revision ID: 29c05e6b6b12
Revises: 09e8d2408d4a
Create Date: 2026-09-20 22:43:06.857320

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29c05e6b6b12"
down_revision: str | Sequence[str] | None = "09e8d2408d4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "embedding_model")
    op.drop_column("documents", "metadata_version")
    op.drop_column("documents", "chunking_version")
    op.drop_column("documents", "parser_version")
    op.drop_column("documents", "processing_version")
    # ### end Alembic commands ###
