"""add embedding model

Revision ID: 29c05e6b6b12
Revises: 09e8d2408d4a
Create Date: 2026-09-20 22:43:06.857320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29c05e6b6b12'
down_revision: Union[str, Sequence[str], None] = '09e8d2408d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_jobs')
    op.add_column('documents', sa.Column('processing_version', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('parser_version', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('chunking_version', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('metadata_version', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'metadata_version')
    op.drop_column('documents', 'chunking_version')
    op.drop_column('documents', 'parser_version')
    op.drop_column('documents', 'processing_version')
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('ingestion_jobs_document_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_jobs_pkey'))
    )
    # ### end Alembic commands ###
