"""add new fields

Revision ID: 31f10bc2b1c3
Revises: c9744455b160
Create Date: 2026-09-06 19:58:52.783529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f10bc2b1c3'
down_revision: Union[str, Sequence[str], None] = 'c9744455b160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('documents', sa.Column('expiration_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('source_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('authority', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('legal_references', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'legal_references')
    op.drop_column('documents', 'authority')
    op.drop_column('documents', 'source_type')
    op.drop_column('documents', 'expiration_date')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
