"""add updated_date

Revision ID: 3d3a7bdf4a8f
Revises: a9ae2d7ce623
Create Date: 2026-09-20 23:21:30.963619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a7bdf4a8f'
down_revision: Union[str, Sequence[str], None] = 'a9ae2d7ce623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
