"""add document search metadata

Revision ID: 4c29abd55148
Revises: ded60c77170b
Create Date: 2026-09-05 16:57:29.433365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c29abd55148'
down_revision: Union[str, Sequence[str], None] = 'ded60c77170b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('countries', sa.ARRAY(sa.String(length=2)), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('effective_date', sa.Date(), nullable=True))
    op.create_index(
        "ix_document_chunks_text_trgm",
        "document_chunks",
        ["text"],
        postgresql_using="gin",
        postgresql_ops={
            "text": "gin_trgm_ops"
        },
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'effective_date')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'countries')
    # ### end Alembic commands ###
