"""nullable True

Revision ID: 61639e45f021
Revises: 0ab42a1b2164
Create Date: 2026-09-05 15:16:48.270874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61639e45f021'
down_revision: Union[str, Sequence[str], None] = '0ab42a1b2164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'page_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_chunks', 'page_end',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'page_end',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_chunks', 'page_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
