"""add source_url

Revision ID: 6f865ee86a7c
Revises: 31f10bc2b1c3
Create Date: 2026-09-06 20:55:50.139310

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f865ee86a7c'
down_revision: str | Sequence[str] | None = '31f10bc2b1c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_url', sa.String(length=2000), nullable=True))
    op.create_unique_constraint(None, 'documents', ['source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'source_url')
    # ### end Alembic commands ###
