"""embeddings nullable

Revision ID: 787bcc981b4c
Revises: 6b024d6dfb31
Create Date: 2026-09-05 16:04:15.033428

"""

from collections.abc import Sequence

import pgvector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787bcc981b4c"
down_revision: str | Sequence[str] | None = "6b024d6dfb31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
        nullable=False,
    )
    # ### end Alembic commands ###
