"""add stored_filename

Revision ID: a9ae2d7ce623
Revises: c9d97b218b31
Create Date: 2026-09-20 23:10:10.887655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ae2d7ce623'
down_revision: Union[str, Sequence[str], None] = 'c9d97b218b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###
