"""sync models with schema drift

Revision ID: fcdc2c58f662
Revises: cb078d2729f0
Create Date: 2026-10-01 21:18:35.212439

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcdc2c58f662"
down_revision: str | Sequence[str] | None = "cb078d2729f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "processing_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "parser_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "chunking_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "metadata_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "ingestion_jobs", "job_type", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "ingestion_jobs",
        "original_filename",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "stored_filename",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "current_step",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "ingestion_jobs",
        "error_code",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "ingestion_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(op.f("uq_content_hash_status"), "ingestion_jobs", type_="unique")
    op.create_index(
        op.f("ix_ingestion_jobs_content_hash"),
        "ingestion_jobs",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_job_type"), "ingestion_jobs", ["job_type"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_job_type"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_content_hash"), table_name="ingestion_jobs")
    op.create_unique_constraint(
        op.f("uq_content_hash_status"),
        "ingestion_jobs",
        ["content_hash", "status"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ingestion_jobs",
        "error_code",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "ingestion_jobs",
        "current_step",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "ingestion_jobs",
        "stored_filename",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "original_filename",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "ingestion_jobs",
        "job_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "documents",
        "metadata_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "documents",
        "chunking_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "documents",
        "parser_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "documents",
        "processing_version",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    # ### end Alembic commands ###
